<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Alpha_numeric extends DB\Validator
{
	public static array $validators = [
		'alpha_numeric' => ['alpha_numeric'],
	];

	public function __construct(\Tests\Fixtures\Record\Alpha_numeric $record)
	{
		parent::__construct($record);
	}
}
