<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Card extends DB\Validator
{
	public static array $validators = [
		'card' => ['card'],
	];

	public function __construct(\Tests\Fixtures\Record\Card $record)
	{
		parent::__construct($record);
	}
}
