<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Cvv extends DB\Validator
{
	public static array $validators = [
		'cvv' => ['cvv'],
	];

	public function __construct(\Tests\Fixtures\Record\Cvv $record)
	{
		parent::__construct($record);
	}
}
