<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Date extends DB\Validator
{
	public static array $validators = [
		'date' => ['date'],
	];

	public function __construct(\Tests\Fixtures\Record\Date $record)
	{
		parent::__construct($record);
	}
}
