<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class DateISO extends DB\Validator
{
	public static array $validators = [
		'dateISO' => ['dateISO'],
	];

	public function __construct(\Tests\Fixtures\Record\DateISO $record)
	{
		parent::__construct($record);
	}
}
