<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Day_month_year extends DB\Validator
{
	public static array $validators = [
		'day_month_year' => ['day_month_year'],
	];

	public function __construct(\Tests\Fixtures\Record\Day_month_year $record)
	{
		parent::__construct($record);
	}
}
