<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Email extends DB\Validator
{
	public static array $validators = [
		'email' => ['email'],
	];

	public function __construct(\Tests\Fixtures\Record\Email $record)
	{
		parent::__construct($record);
	}
}
