<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Enum extends DB\Validator
{
	public static array $validators = [
		'enum' => ['enum:GET,POST,PUT,DELETE'],
	];

	public function __construct(\Tests\Fixtures\Record\Enum $record)
	{
		parent::__construct($record);
	}
}
