<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Integer extends DB\Validator
{
	public static array $validators = [
		'integer' => ['integer'],
	];

	public function __construct(\Tests\Fixtures\Record\Integer $record)
	{
		parent::__construct($record);
	}
}
