<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Maxlength extends DB\Validator
{
	public static array $validators = [
		'maxlength' => ['maxlength'],
		'length' => ['maxlength:20', 'minlength:2'],
	];

	public function __construct(\Tests\Fixtures\Record\Maxlength $record)
	{
		parent::__construct($record);
	}
}
