<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Maxvalue extends DB\Validator
{
	public static array $validators = [
		'maxvalue' => ['maxvalue:10'],
		'value' => ['maxvalue:15', 'minvalue:5'],
	];

	public function __construct(\Tests\Fixtures\Record\Maxvalue $record)
	{
		parent::__construct($record);
	}
}
