<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Minvalue extends DB\Validator
{
	public static array $validators = [
		'minvalue' => ['minvalue:-10'],
	];

	public function __construct(\Tests\Fixtures\Record\Minvalue $record)
	{
		parent::__construct($record);
	}
}
