<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Month_year extends DB\Validator
{
	public static array $validators = [
		'month_year' => ['month_year'],
	];

	public function __construct(\Tests\Fixtures\Record\Month_year $record)
	{
		parent::__construct($record);
	}
}
