<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Number extends DB\Validator
{
	public static array $validators = [
		'number' => ['number'],
	];

	public function __construct(\Tests\Fixtures\Record\Number $record)
	{
		parent::__construct($record);
	}
}
