<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Required extends DB\Validator
{
	public static array $validators = [
		'required' => ['required'],
	];

	public function __construct(\Tests\Fixtures\Record\Required $record)
	{
		parent::__construct($record);
	}
}
