<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Time extends DB\Validator
{
	public static array $validators = [
		'time' => ['time'],
	];

	public function __construct(\Tests\Fixtures\Record\Time $record)
	{
		parent::__construct($record);
	}
}
