<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Unique extends DB\Validator
{
	public static array $validators = [
		'unique' => ['unique'],
	];

	public function __construct(\Tests\Fixtures\Record\Unique $record)
	{
		parent::__construct($record);
	}
}
