<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Url extends DB\Validator
{
	public static array $validators = [
		'url' => ['url'],
	];

	public function __construct(\Tests\Fixtures\Record\Url $record)
	{
		parent::__construct($record);
	}
}
