<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Website extends DB\Validator
{
	public static array $validators = [
		'website' => ['website'],
	];

	public function __construct(\Tests\Fixtures\Record\Website $record)
	{
		parent::__construct($record);
	}
}
