<?php

namespace Tests\Fixtures\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Year_month extends DB\Validator
{
	public static array $validators = [
		'year_month' => ['year_month'],
	];

	public function __construct(\Tests\Fixtures\Record\Year_month $record)
	{
		parent::__construct($record);
	}
}
