<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property int $artistId MySQL type int(11)
 * @property \App\Record\Artist $artist related record
 * @property string $artist MySQL type varchar(255)
 * @property int $plays MySQL type int(11)
 * @property int $rank MySQL type int(11)
 */
abstract class Artist extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'artistId' => ['int(11)', 'int', 11, false, null, true, ],
		'artist' => ['varchar(255)', 'string', 255, false, '', false, ],
		'plays' => ['int(11)', 'int', 11, false, 0, false, ],
		'rank' => ['int(11)', 'int', 11, false, 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['artistId' => true, ];

	protected static string $table = 'artist';
	}
