<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $artist MySQL type varchar(255)
 * @property ?int $artistId MySQL type integer
 * @property int $plays MySQL type integer
 * @property int $rank MySQL type integer
 */
abstract class Artist extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'artist' => ['varchar(255)', 'string', 255, false, false, '', ],
		'artistId' => ['integer', 'int', 0, true, true, ],
		'plays' => ['integer', 'int', 0, false, false, 0, ],
		'rank' => ['integer', 'int', 0, false, false, 0, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['artistId' => true, ];

	protected static string $table = 'artist';
	}
