<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $airDate MySQL type date
 * @property int $episode MySQL type integer
 * @property string $notes MySQL type varchar(255)
 * @property int $repeat MySQL type integer
 * @property int $season MySQL type integer
 * @property ?int $showId MySQL type integer
 * @property \App\Record\Show $show related record
 */
abstract class Show extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'airDate' => ['date', 'string', 10, false, true, null, ],
		'episode' => ['integer', 'int', 0, false, false, 0, ],
		'notes' => ['varchar(255)', 'string', 255, false, false, '', ],
		'repeat' => ['integer', 'int', 0, false, false, 0, ],
		'season' => ['integer', 'int', 0, false, false, 0, ],
		'showId' => ['integer', 'int', 0, true, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['showId' => true, ];

	protected static string $table = 'show';
	}
