<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property int $albumId MySQL type int(11)
 * @property \App\Record\Album $album related record
 * @property int $artistId MySQL type int(11)
 * @property \App\Record\Artist $artist related record
 * @property int $showId MySQL type int(11)
 * @property \App\Record\Show $Show related record
 * @property int $titleId MySQL type int(11)
 * @property \App\Record\Title $title related record
 * @property ?int $second_ArtistId MySQL type int(11)
 * @property \App\Record\Second_Artist $second_Artist related record
 * @property int $sequence MySQL type int(11)
 */
abstract class ShowSequence extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'albumId' => ['int(11)', 'int', 11, false, null, true, ],
		'artistId' => ['int(11)', 'int', 11, false, null, true, ],
		'showId' => ['int(11)', 'int', 11, false, null, true, ],
		'titleId' => ['int(11)', 'int', 11, false, null, true, ],
		'second_ArtistId' => ['int(11)', 'int', 11, true, null, true, ],
		'sequence' => ['int(11)', 'int', 11, false, null, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['showId' => true, 'sequence' => true, ];

	protected static string $table = 'showSequence';
	}
