<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property int $showId MySQL type int(11)
 * @property \App\Record\Show $Show related record
 * @property ?string $airDate MySQL type date
 * @property int $episode MySQL type int(11)
 * @property string $notes MySQL type varchar(255)
 * @property int $repeat MySQL type int(11)
 * @property int $season MySQL type int(11)
 */
abstract class Show extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'showId' => ['int(11)', 'int', 11, false, null, true, ],
		'airDate' => ['date', 'string', 10, true, null, false, ],
		'episode' => ['int(11)', 'int', 11, false, 0, false, ],
		'notes' => ['varchar(255)', 'string', 255, false, '', false, ],
		'repeat' => ['int(11)', 'int', 11, false, 0, false, ],
		'season' => ['int(11)', 'int', 11, false, 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['showId' => true];

	protected static string $table = 'show';
	}
