<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $albumId MySQL type integer
 * @property \App\Record\Album $album related record
 * @property int $artistId MySQL type integer
 * @property \App\Record\Artist $artist related record
 * @property ?int $second_artistId MySQL type integer
 * @property \App\Record\SecondArtist $second_artist related record
 * @property int $sequence MySQL type integer
 * @property int $showId MySQL type integer
 * @property \App\Record\Show $show related record
 * @property int $titleId MySQL type integer
 * @property \App\Record\Title $title related record
 */
abstract class ShowSequence extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'albumId' => ['integer', 'int', 0, false, false, ],
		'artistId' => ['integer', 'int', 0, false, false, ],
		'second_artistId' => ['integer', 'int', 0, false, true, null, ],
		'sequence' => ['integer', 'int', 0, true, false, ],
		'showId' => ['integer', 'int', 0, true, false, ],
		'titleId' => ['integer', 'int', 0, false, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['showId' => true, 'sequence' => true, ];

	protected static string $table = 'showSequence';
	}
